name: Publish on Github & Modrinth
'on':
- pull_request
- workflow_dispatch
env:
  MINECRAFT_VERSION: '1.21'
  JAVA_VERSION: 21
  VERSION: 1.0.0-1.21
  RELEASE_NAME: repair-swapper v1.0.0 for Minecraft 1.21
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Environment Variables
      run: env
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 21
    - name: Make Gradle Wrapper Executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew
    - name: Build
      run: ./gradlew clean build
    - name: Publish (Modrinth/GitHub)
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: Bwu8SwOg
        modrinth-token: ${{env.MODRINTH_TOKEN}}
        modrinth-dependencies: |
          MidnightLib(required)
        github-tag: v${{env.VERSION}}
        github-token: ${{env.GITHUB_TOKEN}}
        name: ${{env.RELEASE_NAME}}
        version: ${{env.VERSION}}
        version-type: beta
        changelog-file: CHANGELOG.md
        loaders: fabric
        game-versions: ${{env.MINECRAFT_VERSION}}
        java: ${{env.JAVA_VERSION}}
